### ISSUE TITLE
samples/zephyr make error

### ISSUE THREAD

**Issue by Jeepgoing** [runtimeco/mcuboot#253]
hello,when i make zephyr hello-world use "make hello1",an error appeared,who can help me:

Traceback (most recent call last):
  File "../../scripts/imgtool.py", line 145, in <module>
    args()
  File "../../scripts/imgtool.py", line 142, in args
    subcmds[args.subcmd](args)
  File "../../scripts/imgtool.py", line 85, in do_sign
    img.sign(key)
  File "/home/liang/work/shared/mcuboot-1.1.0/scripts/imgtool/image.py", line 128, in sign
    sig = key.sign(bytes(self.payload))
  File "/home/liang/work/shared/mcuboot-1.1.0/scripts/imgtool/keys/rsa.py", line 92, in sign
    return self.key.sign(
AttributeError: '_RSAPrivateKey' object has no attribute 'sign'

**Comment by Jeepgoing** [comment]
i have installed scripts/requirements.txt with sudo and without sudo

**Comment by Jeepgoing** [comment]
i have uninstall cryptography,and reinstall cryptography,this problem was solved.
i think when i first install cryptography,maybe i used sudo.

**Comment by aspirine92** [comment]
Actually cryptography package was not installed.

```
pip3 install cryptography
```

No "sudo" required.

**Comment by d3zd3z** [comment]
Generally, should be

    pip3 install -u cryptography

Depending on your distribution. In general, you should *never* use sudo on a pip command.
